# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OLEUI_ErrorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OLE_UIError(object):
    def setupUi(self, OLE_UIError):
        OLE_UIError.setObjectName("OLE_UIError")
        OLE_UIError.resize(649, 250)
        OLE_UIError.setMinimumSize(QtCore.QSize(515, 167))
        OLE_UIError.setMaximumSize(QtCore.QSize(649, 250))
        self.UI_ErrorTitle = QtWidgets.QLabel(OLE_UIError)
        self.UI_ErrorTitle.setGeometry(QtCore.QRect(140, 20, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.UI_ErrorTitle.setFont(font)
        self.UI_ErrorTitle.setObjectName("UI_ErrorTitle")
        self.UI_ErrorIcon = QtWidgets.QLabel(OLE_UIError)
        self.UI_ErrorIcon.setGeometry(QtCore.QRect(30, 80, 81, 81))
        self.UI_ErrorIcon.setText("")
        self.UI_ErrorIcon.setPixmap(QtGui.QPixmap("E:/CDX Volumes/CDX Vol 2 [Digital Artworks]/Others/Emote Design/Facepalm Emote Enlargio+ 512px.png"))
        self.UI_ErrorIcon.setScaledContents(True)
        self.UI_ErrorIcon.setWordWrap(True)
        self.UI_ErrorIcon.setObjectName("UI_ErrorIcon")
        self.UI_Error = QtWidgets.QLabel(OLE_UIError)
        self.UI_Error.setGeometry(QtCore.QRect(140, 75, 481, 111))
        self.UI_Error.setObjectName("UI_Error")
        self.ErrorAcceptButton = QtWidgets.QPushButton(OLE_UIError)
        self.ErrorAcceptButton.setGeometry(QtCore.QRect(280, 200, 81, 31))
        self.ErrorAcceptButton.setObjectName("ErrorAcceptButton")

        self.retranslateUi(OLE_UIError)
        self.ErrorAcceptButton.clicked.connect(OLE_UIError.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OLE_UIError)

    def retranslateUi(self, OLE_UIError):
        _translate = QtCore.QCoreApplication.translate
        OLE_UIError.setWindowTitle(_translate("OLE_UIError", "Dialog"))
        self.UI_ErrorTitle.setText(_translate("OLE_UIError", "Error"))
        self.UI_Error.setText(_translate("OLE_UIError", "{ERROR_TEXT}"))
        self.ErrorAcceptButton.setText(_translate("OLE_UIError", "OK"))
