# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OLEUI_InfoDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OLE_UIInfo(object):
    def setupUi(self, OLE_UIInfo):
        OLE_UIInfo.setObjectName("OLE_UIInfo")
        OLE_UIInfo.resize(649, 250)
        OLE_UIInfo.setMinimumSize(QtCore.QSize(515, 167))
        OLE_UIInfo.setMaximumSize(QtCore.QSize(649, 250))
        self.UI_StatusTitle = QtWidgets.QLabel(OLE_UIInfo)
        self.UI_StatusTitle.setGeometry(QtCore.QRect(140, 20, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.UI_StatusTitle.setFont(font)
        self.UI_StatusTitle.setObjectName("UI_StatusTitle")
        self.UI_StatusIcon = QtWidgets.QLabel(OLE_UIInfo)
        self.UI_StatusIcon.setGeometry(QtCore.QRect(30, 80, 81, 81))
        self.UI_StatusIcon.setText("")
        self.UI_StatusIcon.setPixmap(QtGui.QPixmap(":/UI_Status/Resources/Organiser.png"))
        self.UI_StatusIcon.setScaledContents(True)
        self.UI_StatusIcon.setWordWrap(True)
        self.UI_StatusIcon.setObjectName("UI_StatusIcon")
        self.UI_Status = QtWidgets.QLabel(OLE_UIInfo)
        self.UI_Status.setGeometry(QtCore.QRect(140, 75, 481, 111))
        self.UI_Status.setObjectName("UI_Status")
        self.StatusAcceptButton = QtWidgets.QPushButton(OLE_UIInfo)
        self.StatusAcceptButton.setGeometry(QtCore.QRect(280, 200, 81, 31))
        self.StatusAcceptButton.setObjectName("StatusAcceptButton")

        self.retranslateUi(OLE_UIInfo)
        self.StatusAcceptButton.clicked.connect(OLE_UIInfo.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OLE_UIInfo)

    def retranslateUi(self, OLE_UIInfo):
        _translate = QtCore.QCoreApplication.translate
        OLE_UIInfo.setWindowTitle(_translate("OLE_UIInfo", "Dialog"))
        self.UI_StatusTitle.setText(_translate("OLE_UIInfo", "{STATUS_TITLE}"))
        self.UI_Status.setText(_translate("OLE_UIInfo", "{STATUS_TEXT}"))
        self.StatusAcceptButton.setText(_translate("OLE_UIInfo", "OK"))
