# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './QtUI/OLEHandler_TestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OLEHandlerDialog(object):
    def setupUi(self, OLEHandlerDialog):
        OLEHandlerDialog.setObjectName("OLEHandlerDialog")
        OLEHandlerDialog.resize(514, 172)
        self.buttonBox = QtWidgets.QDialogButtonBox(OLEHandlerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(160, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(OLEHandlerDialog)
        self.label.setGeometry(QtCore.QRect(20, 50, 141, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(OLEHandlerDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_2.setObjectName("label_2")
        self.FileExtractDirectory = QtWidgets.QLineEdit(OLEHandlerDialog)
        self.FileExtractDirectory.setGeometry(QtCore.QRect(180, 50, 201, 21))
        self.FileExtractDirectory.setObjectName("FileExtractDirectory")
        self.ExtractSaveDirectory = QtWidgets.QLineEdit(OLEHandlerDialog)
        self.ExtractSaveDirectory.setGeometry(QtCore.QRect(180, 90, 201, 21))
        self.ExtractSaveDirectory.setObjectName("ExtractSaveDirectory")
        self.label_3 = QtWidgets.QLabel(OLEHandlerDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.FileExtractButton = QtWidgets.QPushButton(OLEHandlerDialog)
        self.FileExtractButton.setGeometry(QtCore.QRect(390, 50, 113, 31))
        self.FileExtractButton.setObjectName("FileExtractButton")
        self.ExtractSaveButton = QtWidgets.QPushButton(OLEHandlerDialog)
        self.ExtractSaveButton.setGeometry(QtCore.QRect(390, 90, 113, 31))
        self.ExtractSaveButton.setObjectName("ExtractSaveButton")
        self.label_4 = QtWidgets.QLabel(OLEHandlerDialog)
        self.label_4.setGeometry(QtCore.QRect(290, 10, 211, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(OLEHandlerDialog)
        self.buttonBox.accepted.connect(OLEHandlerDialog.accept)
        self.buttonBox.rejected.connect(OLEHandlerDialog.reject)
        self.ExtractSaveButton.clicked.connect(OLEHandlerDialog.chooseExtractSave)
        self.FileExtractButton.clicked.connect(OLEHandlerDialog.chooseExtractFile)
        QtCore.QMetaObject.connectSlotsByName(OLEHandlerDialog)

    def retranslateUi(self, OLEHandlerDialog):
        _translate = QtCore.QCoreApplication.translate
        OLEHandlerDialog.setWindowTitle(_translate("OLEHandlerDialog", "Dialog"))
        self.label.setText(_translate("OLEHandlerDialog", "Choose File to Extract:"))
        self.label_2.setText(_translate("OLEHandlerDialog", "Choose Save Location:"))
        self.label_3.setText(_translate("OLEHandlerDialog", "OLEHandler"))
        self.FileExtractButton.setText(_translate("OLEHandlerDialog", "Browse"))
        self.ExtractSaveButton.setText(_translate("OLEHandlerDialog", "Browse"))
        self.label_4.setText(_translate("OLEHandlerDialog", "Created by: TwelfthDoctor1 [2022]"))
