# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OLEUI_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OLEHandlerDialog(object):
    def setupUi(self, OLEHandlerDialog):
        OLEHandlerDialog.setObjectName("OLEHandlerDialog")
        OLEHandlerDialog.resize(697, 265)
        OLEHandlerDialog.setMinimumSize(QtCore.QSize(514, 172))
        self.buttonBox = QtWidgets.QDialogButtonBox(OLEHandlerDialog)
        self.buttonBox.setGeometry(QtCore.QRect(340, 220, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(OLEHandlerDialog)
        self.label.setGeometry(QtCore.QRect(20, 80, 221, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(OLEHandlerDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 221, 16))
        self.label_2.setObjectName("label_2")
        self.FileExtractDirectory = QtWidgets.QLineEdit(OLEHandlerDialog)
        self.FileExtractDirectory.setGeometry(QtCore.QRect(260, 80, 291, 21))
        self.FileExtractDirectory.setObjectName("FileExtractDirectory")
        self.ExtractSaveDirectory = QtWidgets.QLineEdit(OLEHandlerDialog)
        self.ExtractSaveDirectory.setGeometry(QtCore.QRect(260, 120, 291, 21))
        self.ExtractSaveDirectory.setObjectName("ExtractSaveDirectory")
        self.label_3 = QtWidgets.QLabel(OLEHandlerDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.FileExtractButton = QtWidgets.QPushButton(OLEHandlerDialog)
        self.FileExtractButton.setGeometry(QtCore.QRect(570, 70, 113, 31))
        self.FileExtractButton.setObjectName("FileExtractButton")
        self.ExtractSaveButton = QtWidgets.QPushButton(OLEHandlerDialog)
        self.ExtractSaveButton.setGeometry(QtCore.QRect(570, 110, 113, 31))
        self.ExtractSaveButton.setObjectName("ExtractSaveButton")
        self.label_4 = QtWidgets.QLabel(OLEHandlerDialog)
        self.label_4.setGeometry(QtCore.QRect(410, 10, 271, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.OLEUI_Version = QtWidgets.QLabel(OLEHandlerDialog)
        self.OLEUI_Version.setGeometry(QtCore.QRect(20, 230, 321, 16))
        self.OLEUI_Version.setObjectName("OLEUI_Version")

        self.retranslateUi(OLEHandlerDialog)
        self.buttonBox.accepted.connect(OLEHandlerDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(OLEHandlerDialog.reject) # type: ignore
        self.ExtractSaveButton.clicked.connect(OLEHandlerDialog.chooseExtractSave) # type: ignore
        self.FileExtractButton.clicked.connect(OLEHandlerDialog.chooseExtractFile) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(OLEHandlerDialog)

    def retranslateUi(self, OLEHandlerDialog):
        _translate = QtCore.QCoreApplication.translate
        OLEHandlerDialog.setWindowTitle(_translate("OLEHandlerDialog", "Dialog"))
        self.label.setText(_translate("OLEHandlerDialog", "Choose File to Extract:"))
        self.label_2.setText(_translate("OLEHandlerDialog", "Choose Save Location:"))
        self.label_3.setText(_translate("OLEHandlerDialog", "OLEHandler"))
        self.FileExtractButton.setText(_translate("OLEHandlerDialog", "Browse"))
        self.ExtractSaveButton.setText(_translate("OLEHandlerDialog", "Browse"))
        self.label_4.setText(_translate("OLEHandlerDialog", "Created by: TwelfthDoctor1 [2022]"))
        self.OLEUI_Version.setText(_translate("OLEHandlerDialog", "OLEHandler Version: {VERSION_NAME}"))
